name: 🔥 Destroy All

on:
  workflow_dispatch:
jobs:
  tfm-destroy:
    name: 🧹 Destroy All workspaces
    uses: ./.github/workflows/shared-tf-apply.yml
    with:
      workspaces: "['tst/arepabank', 'tst/tacobank', 'acc/arepabank', 'acc/tacobank', 'prd/arepabank', 'prd/tacobank']"
      destroy-mode: true
      apply: true
    secrets: inherit
